# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: "Calebs Blog"
description: "My website. I have a blog and stuff."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year-:month/:title.html

# Author Info
author_name:        "Caleb Fetzer"
author_email:       caleb.fetzer@gmail.com
github_username:    lqze # GitHub username

# Markdown
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Reading
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "*.sh", "*.lock" ]
